---
name: terraform-provider-credhub
platforms:
- darwin/amd64
- linux/amd64
- windows/amd64
- linux/386
- windows/386
metadata:
  shortname: credhub
asset_template: {{.Name}}_{{.OS}}_{{.Arch}}
install_path: {{.Home}}/.terraform.d/providers/{{.Name}}
install:
- |
  grep -Fxq "providers {" ~/.terraformrc &> /dev/null
  if [[ $? != 0 ]]; then
  cat <<EOF >> ~/.terraformrc
  providers {
  {{.Metadata.shortname}} = "{{.Home}}/.terraform.d/providers/{{.Name}}"
  }
  EOF
  else
  grep -Fxq "{{.Metadata.shortname}}" ~/.terraformrc &> /dev/null
  if [[ $? != 0 ]]; then
  echo "${NAME}-${VERSION} has been installed."
  exit 0
  fi
  awk '/providers {/ { print; print "{{.Metadata.shortname}} = \"provider_path\""; next }1' ~/.terraformrc > /tmp/.terraformrc
  mv /tmp/.terraformrc ~/
  fi
